<Project>
    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <PropertyGroup>
        <Authors>Heuristic and Evolutionary Algorithms Laboratory (HEAL)</Authors>
        <Company>University of Applied Sciences Upper Austria</Company>
        <Copyright>(c) Heuristic and Evolutionary Algorithms Laboratory (HEAL)</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.19.0.132793">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
