<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <AssemblyName>HEAL.HeuristicLib.Tests.Experimental</AssemblyName>
        <RootNamespace>HEAL.HeuristicLib.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\HeuristicLib.Experimental\HeuristicLib.Experimental.csproj" />
        <ProjectReference Include="..\..\src\HeuristicLib.PythonInterop\HeuristicLib.PythonInterop.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="xunit.analyzers" Version="2.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shouldly" />
        <Using Include="Xunit" />
        <Using Include="System.Collections.Immutable" />
        <Using Include="HEAL.HeuristicLib.Collections" />
    </ItemGroup>
</Project>
