<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <AssemblyName>HEAL.HeuristicLib.Tests</AssemblyName>
        <RootNamespace>HEAL.HeuristicLib.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\HeuristicLib\HeuristicLib.csproj" />
        <ProjectReference Include="..\..\analyzers\HeuristicLib.Analyzers\HeuristicLib.Analyzers.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="Shouldly" Version="4.3.0" />
        <PackageReference Include="System.Reactive" Version="6.1.0" />
        <PackageReference Include="xunit.analyzers" Version="1.27.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Shouldly" />
        <Using Include="Xunit" />
        <Using Include="System.Collections.Immutable" />
        <Using Include="HEAL.HeuristicLib.Collections" />
    </ItemGroup>
</Project>
